# prefer from cmake distribution (if it exists)
if(EXISTS ${CMAKE_ROOT}/Modules/FindCDBAPI.cmake)
  include(${CMAKE_ROOT}/Modules/FindCDBAPI.cmake)

  if(CDBAPI_FOUND)
    return()
  endif()
endif()

SET(CDBAPI_FOUND "NO")

FIND_PATH(CDBAPI_INCLUDE_DIR Cee_CdbApi.h)

FIND_LIBRARY(CDBAPI_LIBRARY_DEBUG
    NAMES CeeCdbApi
    PATH_SUFFIXES
    lib64
    ms100_64_d
)

FIND_LIBRARY(CDBAPI_LIBRARY_RELEASE
    NAMES CeeCdbApi
    PATH_SUFFIXES
    lib64
    ms100_64_r
)

set (CDBAPI_LIBRARY_RELWITHDEBINFO CDBAPI_LIBRARY_RELEASE)
set (CDBAPI_LIBRARY CDBAPI_LIBRARY_${CMAKE_BUILD_TYPE})

FIND_LIBRARY(CEEREADER_LIBRARY_DEBUG
    NAMES CeeReader
    PATH_SUFFIXES
    lib64
    ms140_64_d
)

FIND_LIBRARY(CEEREADER_LIBRARY_RELEASE
    NAMES CeeReader
    PATH_SUFFIXES
    lib64
    ms140_64_d
)

set (CEEREADER_LIBRARY_RELWITHDEBINFO CEEREADER_LIBRARY_RELEASE)
set (CEEREADER_LIBRARY CEEREADER_LIBRARY_${CMAKE_BUILD_TYPE})

IF(CDBAPI_LIBRARY AND CEEREADER_LIBRARY AND CDBAPI_INCLUDE_DIR)
    SET(CDBAPI_FOUND "YES")
ENDIF(CDBAPI_LIBRARY AND CEEREADER_LIBRARY AND CDBAPI_INCLUDE_DIR)
